var ålder = 17;
var tal1 =12;
var tal2 =24;
var summa =tal1+tal2;
var namn ="awf";
var nman = "faw";
var namnman = namn +" "+nman;
var hob="aga";
var men =namnman + "'s"+" " + "afa"+" "+hob;
alert(men); 